# Generated by Django 3.2.5 on 2021-07-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_item_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_listing',
            name='image',
        ),
    ]
