# Generated by Django 3.2.5 on 2021-07-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_item_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_listing',
            name='ImageLink',
            field=models.URLField(default='https://www.google.com/url?sa=i&url=http%3A%2F%2Fwww.macedonrangeshalls.com.au%2Fimage-not-found%2F&psig=AOvVaw1uPpQ-7XrX6_JcHaaoGxeZ&ust=1627751776881000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCLiU_4Wmi_ICFQAAAAAdAAAAABAD'),
        ),
    ]
